file = open('Music.txt')
print(file.read())
file.close()
file_read = open('Music.txt','r')
print("File in Read mode is: ")
print(file_read.read())
file_read.close()
file_write = open('Music.txt','r')
print("File in Write mode is: ")
print(file_write.write())
file_write.close()
file_append= open('Music.txt','r')
print("File in Append mode is: ")
print(file_append.append())
file_append.close()